### ISSUE TITLE
Shouldn't use the babel require hook

### ISSUE THREAD

**Issue by leoetlino** [Innovate-Technologies/id3-writer-js#2]
As this is a library, it really shouldn't use the babel require hook, since this will force users to use Babel for their whole app, and for a library, this really isn't something it should do.

The site also warns about this:

>**Not suitable for libraries**
>The require hook automatically hooks itself into all node requires. This will pollute the global scope and introduce conflicts. Because of this it's not suitable for libraries, if however you're writing an application then it's completely fine to use.

**Comment by meyskens** [comment]
thx will change that

**Comment by meyskens** [comment]
fixed in latest commit.
